### ISSUE TITLE
Docker login

### ISSUE THREAD

**Issue by SolWski** [KaiLicht/DataScience_Toolbox#2]
It might be worth adding to the docker login that the $ in $oauthtoken has to be escaped, it took me far too long to figure that out, i.e.  
`docker login -u '$oauthtoken' -p pass123haha nvcr.io`

**Comment by KaiLicht** [comment]
My method seems to only work in interactive mode:
![screenshot from 2018-06-14 13-50-04](https://user-images.githubusercontent.com/13822742/41410486-ee9da888-6fd9-11e8-9986-493ce3d369ce.png)

But good point, I've added that to the tutorial!
